admin/models/Voyage.php
<?php

namespace app\models;

use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Linkable;

/**
 * This is the model class for table "voyage".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property integer $organisation_id
 * @property string $date_start
 * @property string $date_end
 * @property boolean $is_finished
 * @property integer $expected_cost
 *
 * @property Consumption[] $consumptions
 * @property Employee $employee
 * @property Organisation $organisation
 */
class Voyage extends \yii\db\ActiveRecord implements Linkable
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'voyage';
    }

    const SCENARIO_SET_END = 'set_end';
    const SCENARIO_CHANGE_EMPLOYEE = 'change_employee';
    const SCENARIO_CHANGE_DESTINATION = 'change_destination';

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['employee_id', 'organisation_id', 'date_start', 'expected_cost'], 'required'],
            [['employee_id', 'organisation_id', 'expected_cost'], 'integer'],
            [['is_finished'], 'boolean'],
            [['date_start', 'date_end'], 'date', 'format' => 'YYYY-MM-DD'],
            [['employee_id'], 'exist', 'skipOnError' => false, 'targetClass' => Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['organisation_id'], 'exist', 'skipOnError' => false, 'targetClass' => Organisation::className(), 'targetAttribute' => ['organisation_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'employee_id' => 'Работник',
            'organisation_id' => 'Организация',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окончания',
            'is_finished' => 'Завершено',
            'expected_cost' => 'Ожидаемые расходы'
        ];
    }

    public function scenarios()
    {
        return ArrayHelper::merge(parent::scenarios(), [
            self::SCENARIO_SET_END => ['date_end', 'is_finished'],
            self::SCENARIO_CHANGE_EMPLOYEE => ['employee_id'],
            self::SCENARIO_CHANGE_DESTINATION => ['organisation_id']
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsumptions()
    {
        return $this->hasMany(Consumption::className(), ['voyage_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrganisation()
    {
        return $this->hasOne(Organisation::className(), ['id' => 'organisation_id']);
    }

    /**
     * @inheritdoc
     * @return \app\models\queries\VoyageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\queries\VoyageQuery(get_called_class());
    }

    public function fields(){
        return [
            'id' => 'id',
            'organisation' => function($model, $field){
                return $model->organisation->name;
            },
            'date_start' => 'date_start',
            'is_finished' => 'is_finished',
            'consumptions' => 'consumptions'
        ];
    }


    public function getLinks()
    {
        return [
            'self' => Url::to(['voyage/view', 'id' => $this->id], true)
        ];
    }
}

admin/controllers/EmployeeController.php
<?php

namespace admin\controllers;

use app\models\Department;
use common\models\User;
use dektrium\user\models\Token;
use Yii;
use app\models\Employee;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Employee::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Employee(['scenario' => 'create']);
        $user = new User(['scenario' => 'create']);

        $post = Yii::$app->request->post();

        if ($model->load($post)  && $user->load($post) ) {
            $valid = $model->validate();
            $valid = $valid && $user->validate();
            if($valid){
                $user->save(false);
                $auth = \Yii::$app->authManager;
                $role = $auth->getRole('employee');
                if(!$role){
                    $role = $auth->createRole('employee');
                    $auth->add($role);

                }
                $auth->assign($role, $user->id);
                $model->user_id = $user->id;
                $model->save(false);
                return $this->redirect(['index']);
            }
        }
        return $this->render('create', [
            'model' => $model,
            'user' => $user,
            'departments' => Department::find()->all()
        ]);
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $user = User::findOne(['id' => $model->user_id]);
        $user->scenario = 'update';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'user' => $user,
                'departments' => Department::find()->all()
            ]);
        }
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

admin/controllers/OrganisationController.php
<?php

namespace admin\controllers;

use app\models\City;
use Yii;
use app\models\Organisation;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrganisationController implements the CRUD actions for Organisation model.
 */
class OrganisationController extends Controller
{


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Organisation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Organisation::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Organisation model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Organisation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Organisation();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'cities' => City::find()->all()
            ]);
        }
    }

    /**
     * Updates an existing Organisation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'cities' => City::find()->all()
            ]);
        }
    }

    /**
     * Deletes an existing Organisation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Organisation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Organisation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Organisation::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

admin/controllers/VoyageController.php
<?php

namespace admin\controllers;

use app\models\Consumption;
use app\models\Employee;
use app\models\Organisation;
use Yii;
use app\models\Voyage;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * VoyageController implements the CRUD actions for Voyage model.
 */
class VoyageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Voyage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Voyage::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Voyage model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Voyage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Voyage();

        $employees = Employee::getFreeEmployers();

        $users = [];
        foreach ($employees as $employee){
            $tmp['id'] = $employee->id;
            $tmp['name'] = $employee->user->username;
            $users[] = $tmp;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->employee->setBusy();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'users' => $users,
                'organisations' => Organisation::find()->asArray()->all()
            ]);
        }
    }

    /**
     * Updates an existing Voyage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $users = [];



        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'organisations' => Organisation::find()->asArray()->all(),
                'users' => $users
            ]);
        }
    }

    /**
     * Deletes an existing Voyage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Voyage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Voyage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Voyage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionConsumption($voyage_id){

        $dataProvider = new ActiveDataProvider([
            'query' => Consumption::find()->where(['voyage_id' => $voyage_id]),
        ]);

        return $this->render('consumption', [
            'dataProvider' => $dataProvider,
            'voyage_id' => $voyage_id
        ]);
    }
}

admin/views/voyage/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;
use admin\widgets\SwitchBtn;


/* @var $this yii\web\View */
/* @var $model app\models\Voyage */
/* @var $form yii\widgets\ActiveForm */
/* @var $users \common\models\User[] */
/* @var $organisations \app\models\Organisation[] */
?>

<div class="voyage-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'employee_id')->widget(Select2::className(), [
            'data' => ArrayHelper::map($users, 'id', 'name'),
            'language' => 'ru'

    ]) ?>

    <?= $form->field($model, 'organisation_id')->widget(Select2::className(), [
            'data' => ArrayHelper::map($organisations, 'id', 'name'),
    ]) ?>

    <?= $form->field($model, 'expected_cost'); ?>

    <?= $form->field($model, 'date_start')->widget(DatePicker::className(), [
        'removeButton' => false,
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
            'startDate' => date('Y-m-d')
        ]
    ])  ?>

    <?= $form->field($model, 'date_end')->widget(DatePicker::className(), [
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd'
        ]
    ]) ?>

    <?= $form->field($model, 'is_finished')->widget(SwitchBtn::className(), [
        'options' => [
            'onText' => 'Завершено',
            'offText' => '',
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/voyage/consumption.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Расходы';
$this->params['breadcrumbs'][] = ['label' => 'Командировки', 'url' => ['/voyage']];
$this->params['breadcrumbs'][] = $voyage_id;
$this->params['breadcrumbs'][] = $this->title;

/* @var $this \yii\web\View */

?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'article',
        'actual_cost',
    ]
]);

admin/views/voyage/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Voyage */

$this->title = Yii::t('app', 'Создать Командировку');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Командировки'), 'url' => ['index']];
?>
<div class="voyage-create">

    <?= $this->render('_form', [
        'model' => $model,
        'users' => $users,
        'organisations' => $organisations
    ]) ?>

</div>

admin/views/voyage/index.php
<?php

use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap\Html;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Командировки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="voyage-index">
    <p>
        <a class="btn btn-success" href="<?= Url::to(['/voyage/create']) ?>"><span class="glyphicon glyphicon-plus"></span></a>
    </p>

<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'employee.user.username',
                'label' => 'Работник',
                'value' => function($model){
                    return Html::a($model->employee->user->username, ['employee/view', 'id' => $model->employee->id]);
                },
                'format' => 'html',
            ],
            [
                'attribute' => 'organisation.name',
                'label' => 'Организация',
                'value' => function($model){
                    return Html::a($model->organisation->name, ['organisation/view', 'id' => $model->organisation->id]);
                },
                'format' => 'html',
            ],
            'date_start',
            'date_end',
            [
                'attribute' => 'is_finished',
                'label' => 'Завершено',
                'value' => function($model){
                    return $model->is_finished ?
                        Html::tag('span', 'Да', ['class' => 'label label-success']) :
                        Html::tag('span', 'Нет', ['class' => 'label label-danger']);
                },
                'format' => 'html'
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template'=>'{consumption} {update} {delete}',
                'buttons'=>[
                    'consumption' => function ($url, $model) {
                        return Html::a('<span class="fa fa-table"></span>', Url::to(['voyage/consumption', 'voyage_id' => $model->id]));
                    }
                ]
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

admin/views/voyage/update.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;
use admin\widgets\switchbtn\SwitchBtn;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\models\Voyage */

$this->title = Yii::t('app', 'Обновить {modelClass}: ', [
    'modelClass' => 'Командировка',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Командировки'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="voyage-update">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'employee_id')->textInput(['disabled' => true, 'value' => $model->employee->user->username]) ?>

    <?= $form->field($model, 'organisation_id')->textInput(['disabled' => true, 'value' => $model->organisation->name]) ?>

    <?= $form->field($model, 'date_start')->widget(DatePicker::className(), [
        'removeButton' => false,
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
            'startDate' => date('Y-m-d')
        ]
    ])  ?>

    <?= $form->field($model, 'date_end')->widget(DatePicker::className(), [
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
        ]
    ]) ?>

    <?= $form->field($model, 'is_finished')->widget(SwitchBtn::className(), [
        'options' => [
            'onText' => 'Завершено',
            'offText' => '',
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/voyage/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Voyage */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Voyages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="voyage-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'employee_id',
            'organisation_id',
            'date_start',
            'date_end',
            'is_finished',
        ],
    ]) ?>

</div>